config/routes.rb
Rails.application.routes.draw do
  root to: 'index#show'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  get '/admin' => 'users#admin'
  get '/index' => 'index#show'

  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  before_save(:titleize_product)
  scope :most_recent, -> { order(created_at: :desc).limit(3)}
  scope :american, -> { where(country_of_origin: "American")}
  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, products.country_of_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(3)
    )}

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates_length_of :content_body, maximum: 250, minimum: 50
  validates_numericality_of :rating, less_than_or_equal_to: 5
  validates_numericality_of :rating, greater_than_or_equal_to: 0
  before_save(:titleize_review)

  private
    def titleize_review
      self.author = self.author.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You need to sign in to view this page."
      redirect_to '/signin'
    end
  end

  def authorize_admin
    if !(current_user && current_user.admin)
      flash[:alert] = "You need admin privileges. Please sign in with an admin account"
      redirect_to '/signin'
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
    @products = Product.all
    render :show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize_admin, only: [:new, :create, :update, :edit, :destroy]

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, only: [:new, :create]
  before_action :authorize_admin, only: [:update, :edit, :destroy]

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
      flash[:notice] = "Review successfully added!"
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      @product = Product.find(params[:product_id])
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try signing in again or sign up to create an account."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]
  before_action :authorize_admin, only: [:admin, :edit, :destroy] #method, not path

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    flash[:notice] = "You've successfully signed up!"
    session[:user_id] = @user.id
    redirect_to '/'
  else
    flash[:alert] = "There was a problem signing up."
    redirect_to '/signup'
  end
end

def admin
    @users = User.all
    render :admin
end

def edit
  @user = User.find(params[:id])
  render :edit
end

def destroy
  @users = User.all
  if User.find(session[:user_id]) == User.find(params[:id])
    flash[:notice] = "NO"
    render :admin_user
  else
    @user = User.find(params[:id])
    @user.destroy
    render :admin_user
  end
end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/index/show.html.erb
<h1>Mario&#39;s Speciality Food Products</h1>
<div class="row">
  <div class="col-sm-4">
    <h3>About us</h3>

    <p>The landing page should include basic information about the company and should allow users to easily navigate to other areas of the site. This page should also include the three most recently added products and the product with the most reviews. See more information in the Scopes section below.</p>
    <br><br>

    <h3>Most Recent Products</h3>
    <% if @products.any? %>
      <ul>
        <% @products.most_recent.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>There are no products yet.</p>
    <% end %>
    <br><br>

    <h3>Most Reviewed Products</h3>
    <% if @products.any? %>
      <ol>
        <% @products.most_reviews.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ol>
    <% else %>
      <p>There are no products yet.</p>
    <% end %>
    <br><br>

    <h3>American Products</h3>
    <% if @products.any? %>
      <ul>
        <% @products.american.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>There are no American products available.</p>
    <% end %>
  </div>
  <div class="col-sm-1"> </div>
  <div class="col-sm-4">
    <div class = "all_product">
      <h3>All Available Products</h3>
      <% if @products.any? %>
        <ol>
          <% @products.each do |product| %>
            <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ol>
      <% else %>
        <p>There are no products yet.</p>
      <% end %>
    </div>
  </div>
</div>
    

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products and Reviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand abs" >Marios SuperMart</a>
      <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="collapseNavbar">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/products">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/admin">Admin</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <% if current_user %>
              <%# <a class="nav-link" href="/signout">Sign out</a> %>
              <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
            <% else %>
              <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <span id="alert"><%= flash[:alert] %></span>
    <span id="notice"><%= flash[:notice] %></span>
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Mario&#39;s Speciality Food Products</h1>
<h2>Product List:</h2>
<% if @products.any? %>
<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>
<br>
<% if current_user && current_user.admin %>
  <h2 class="admin">Admin only</h2>
  <p><%= link_to "Add a new product", new_product_path %></p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <h2>Product Details</h2>
    <h4>Name: <%= @product.name %></h4>
    <h4>price: $<%= @product.cost %></h4>
    <h4>Nationality: <%= @product.country_of_origin %></h4> <br><br>
    <% if current_user && current_user.admin %>
      <h2 class="admin">Admin only</h2>
      <ul>
        <li><%= link_to "Edit product", edit_product_path(@product) %></li>
        <li><%= link_to "Delete product", product_path(@product),
                                :data => {:confirm => "Are you sure?",
                                              :method => "delete"} %></li>
      </ul>
    <% end %>
  </div>
  <div class="col-sm-4">
  <h2>Reviews</h2>
    <% if @product.reviews.any? %>

      <% @product.reviews.each do |review| %>
        <ul>
          <li>
            <%= link_to review.author, product_review_path(@product, review) %>
          </li>
        </ul>
      <% end %>
    <% else %>
      <p>No reviews are listed for this product.</p>
    <% end %>

    <p><%= link_to "Add a review", new_product_review_path(@product) %></p>
    <br>
    <p><%= link_to "Return to Homepage", '/' %></p>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Author: <%= @review.author %></h1>
<h2>Product: <%= @product.name %></h2>
<h3>Rating: <%= @review.rating %></h3>
<h3>Review: <%= @review.content_body %></h3><br>
<p><%= link_to "Return to product", product_path(@product) %></p><br><br>
<% if current_user && current_user.admin %>
  <h2 class="admin">Admin only</h2>
  <ul>
    <li><%= link_to "Edit review", edit_product_review_path(@product, @review) %></li>
    <li><%= link_to "Delete review", product_review_path(@product, @review),
                            :data => {:confirm => "Are you sure?",
                                          :method => "delete"} %></li>
  </ul>
<% end %>

app/views/users/admin.html.erb
<% if @users.any? %>
  <h4>Here are the users in the database. (No edit priveledges yet!)</h4>

  <% @users.each do |user| %>
    <ul>
      <li>
      <%= user.email%>
      <% if user.admin %>
      (Admin)
      <% end %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>There are no users.</p>
<% end %>

app/views/users/edit.html.erb
<p><%= link_to "Delete user", user_path(@user),
                                      :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %></p>


<p><%= link_to "Return to users list", admin_path %></p>

app/views/users/new.html.erb
<h2> Sign up</h2><br>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>